# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('album_title', models.CharField(blank=True, max_length=64, verbose_name='Title')),
                ('album_description', models.TextField(blank=True, verbose_name='Description')),
                ('published_status', models.CharField(choices=[('Pri', 'Private'), ('Shr', 'Shared'), ('Pub', 'Public')], default='Pri', max_length=3, verbose_name='Published Status')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.ImageField(upload_to='photo_files/%Y-%m-%d')),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('published_status', models.BooleanField(verbose_name='Published Status')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=7, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=7, verbose_name='Longitude')),
                ('camera', models.CharField(blank=True, max_length=48, verbose_name='Camera')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('albums', models.ManyToManyField(to='imager_images.Album')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='imager_images.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
