# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_models_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to=imager_images.models.user_directory_path),
        ),
    ]
