# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0007_Alter_field_upload_on_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to=imager_images.models.user_directory_path),
        ),
    ]
