# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0008_change_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published_status',
            field=models.CharField(choices=[('Pri', 'Private'), ('Shr', 'Shared'), ('Pub', 'Public')], default='Pri', max_length=3, verbose_name='Published Status'),
        ),
    ]
