# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_addr', models.CharField(blank=True, max_length=128, verbose_name='Street Address')),
                ('unit', models.CharField(blank=True, max_length=8, verbose_name='Unit')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=4, verbose_name='state')),
                ('post_code', models.CharField(blank=True, max_length=5, verbose_name='Postal Code')),
            ],
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(blank=True, max_length=64, verbose_name='Camera Type')),
            ],
        ),
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography_type', models.CharField(choices=[('Nature', 'Nature'), ('Portrait', 'Portrait'), ('Family', 'Family'), ('Urban', 'Urban'), ('Astronomy', 'Astronomy')], max_length=32, verbose_name='Photography Type')),
                ('imager_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photography_type', to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(blank=True, max_length=64, verbose_name='Social Medial Type')),
                ('social_url', models.CharField(blank=True, max_length=64, verbose_name='Social Media URL')),
                ('imager_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='imager_profile.ImagerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='cameratype',
            name='imager_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_type', to='imager_profile.ImagerProfile'),
        ),
        migrations.AddField(
            model_name='address',
            name='imager_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='imager_profile.ImagerProfile'),
        ),
    ]
