# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=7, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=7, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
