# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_changed_photo_album_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(blank=True, to='imager_images.Album'),
        ),
    ]
