# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_album_and_cover_photo_can_be_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
